on:
  - push

jobs:
  install:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm i
        working-directory: web


      - name: ESLint
        run: pnpm lint
        working-directory: web

      - name: Build
        run: pnpm build
        working-directory: web
